dags:
  persistence:
    enabled: false  # Disable PVC if using git-sync
  gitSync:
    enabled: true
    repo: "https://github.com/rondondaniel/python-airflow-dags.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    wait: 60  # Sync interval in seconds
    subPath: "dags"  # DAGs are in the 'dags/' folder of the repo
